apiVersion: v1
kind: ConfigMap
metadata:
  name: ncba-config
  namespace: default
data:
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQLDialect"
  SPRING_JPA_SHOW_SQL: "false"
  SERVER_PORT: "8080"
